

server:
  port: 8081

spring:
  application:
    name: post-services
    
management:
  endpoints:
    web:
      exposure:
        include: refresh
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

post:
  welcome-meassage: "welcome"
  datasource:
    url: jdbc:mysql://localhost:3306/post_db
    username: root
    password: "@Mysql143"
    driver-class-name: com.mysql.cj.jdbc.Driver

