spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/mydb
    username: root
    password: '@Mysql143'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
user:
  nick-name: 'ram'
management:
  endpoints:
     web:
       exposure:
         include: refresh

server:
  port: 8081
